### ISSUE TITLE
Not able to compile under Mac OS X

### ISSUE THREAD

**Issue by GregDunn1953** [virtualagc/virtualagc#1068]
Attempting to compile this under OS X causes the compile to fail with multiple instances of

`/bin/sh: DGDBMI: command not found
`

If you run instead

```
configure
make
sudo make install

```
The compile fails with 

```
/bin/sh: wx-config: command not found
/bin/sh: wx-config: command not found
In file included from yaDEDA2.cpp:50:
./yaDEDA2.h:36:10: fatal error: 'wx/wx.h' file not found
#include <wx/wx.h>
         ^~~~~~~~~
1 error generated.
make[1]: *** [yaDEDA2] Error 1
make: *** [yaDEDA2] Error 2

```

Running under OS X 10.13.6, current patch level.

**Comment by rburkey2005** [comment]
@GregDunn1953, I fear that since I have no way to actually work with 10.13.x, my comments may be worthless, but I'll give it a shot.  It's not entirely clear which of the two sets of [Mac OS X build instructions](http://www.ibiblio.org/apollo/download.html#Mac_OS_X) you're following, but since the 32-bit instructions are prerequisites for the 64-bit instructions, let's start with those.  

The error message you're getting is "wx-config: command not found".  That would typically mean either that wxWidgets is not installed properly (step #3 of the one-time setup instructions) or that your PATH is not set up correctly (step #b of the "Building Virtual AGC" instructions).

What happens if you simply run the command "wx-config" from the command line?  I would predict that you get a "command not found" error.

**Comment by GregDunn1953** [comment]
Thanks for the response!  I am following the build instructions at 
https://github.com/virtualagc/virtualagc
under "Building the Virtual AGC software - Mac OS X"  and yes, when I enter wx-config I do get a "command not found".

After a little bit of flailing around (the wxWidgets site hides its download instructions pretty well) I installed it and wx-config now gives the standard usage info when I invoke it.

Attempting to build again, things go seemingly pretty well trying to build the AGC application again, but after failing to build TRIVIUM it ends here:

```
/Library/Developer/CommandLineTools/usr/bin/make PREFIX=/usr/local NVER=\\\"2017-06-19\\\" CFLAGS="-DALLOW_BSUB" CURSES="-lcurses" LIBS2=" " NOREADLINE=yes ReadlineForWin32= default EXT= -C yaDEDA2 DEV_STATIC=yes
g++ \
		`wx-config --cxxflags`  \
		-o yaDEDA2 yaDEDA2.cpp -x c ../yaAGC/agc_utilities.c ../yaAGC/agc_engine.c ../yaAGC/Backtrace.c ../yaAGC/random.c ../yaAGC/SocketAPI.c ../yaAGC/rfopen.c \
		`wx-config --libs` \
		
In file included from yaDEDA2.cpp:50:
In file included from ./yaDEDA2.h:36:
In file included from /usr/local/include/wx-3.1/wx/wx.h:15:
In file included from /usr/local/include/wx-3.1/wx/object.h:19:
In file included from /usr/local/include/wx-3.1/wx/memory.h:15:
In file included from /usr/local/include/wx-3.1/wx/string.h:37:
/usr/local/include/wx-3.1/wx/strvararg.h:27:18: fatal error: 'tr1/type_traits' file not found
        #include <tr1/type_traits>
                 ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [yaDEDA2] Error 1
make: *** [yaDEDA2] Error 2
 
```

**Comment by rburkey2005** [comment]
@GregDunn1953 This is once again a wxWidgets error, but this time it's a problem building the program yaDEDA2.   I googled "wxwidgets fatal error tr1/type_traits file not found" and found a post on the wxWidgets forum that seems to describe the exact problem you encountered, and provides the user's solution to it:   https://forums.wxwidgets.org/viewtopic.php?t=42268

Unfortunately, the solution given in that post involves building wxWidgets itself from source, using a special configuration setting, rather than installing it from MacPorts.  That's not difficult --- or so I'd like to say, but I obviously can't guarantee it since I have no way to try it myself --- but it is rather time-consuming.  You might also try doing the same google search I mentioned above for yourself, and looking at the many other search hits to see if any of them has a more palatable solution.

If that doesn't work for you, the last-resort thing that can be done is simply not to build yaDEDA2.
yaDEDA2 is the simulation of the keyboard/display unit used with the Abort Guidance System (AGS), and is likely something you don't even need if you're just interested in playing with the AGC, since the AGS is an entirely different computer in the LM.  I've just now tried that out, and it's a bit trickier than I hoped, so I don't actually have the full details how to do it at the moment.  If it turns out to absolutely be the only thing that will help you, I can work out those details ... but it would be better to first make sure that none of the google hits for the problem work for you.

**Comment by lcvisser** [comment]
After a couple of hours messing around I think I have to conclude that currently it's virtually impossible to build and run VirtualAGC on newer MacOS X versions (I'm on 11.2), for the following reasons:

 1. MacOS has dropped all 32-bit support and Xcode/Developer tools also doesn't support it anymore.
 2. WxWidgets-2.8 insists to be compiled for 32-bit and thus won't compile
 3. WxWidgets-3.2 does compile on macOS 64-bit and while I can get Virtual AGC to compile against WxWidgets-3.2, the application immediately crashes on startup.

I'm not sure if there are still 32-bit system libraries available for macOS, but I'd say that it might be better to move to WxWidgets 3.2 instead, if that is feasible.

**Comment by rburkey2005** [comment]
@lcvisser I'll look into wxWidgets 3.2, though as I guess my earlier comments implied, I'll only be able to do it on Linux.  If I can make it work there, perhaps it will work on Mac OS X as well, though I'll have to rely on you to tell me whether it does or not.  I'll let you know if/when I think it's worth trying.

**Comment by rburkey2005** [comment]
@lcvisser I may be confused, but I think that there is no wxWidgets 3.2.  The development branch is 3.1.x, so that the next stable release will be 3.2.  But I can certainly look into 3.1.4 (the latest).  If the problem turns out to be developmental bugs in 3.1.x, I'm obviously not going to be able to do much about it.

**Comment by lcvisser** [comment]
The [docs](https://docs.wxwidgets.org/3.0/page_introduction.html) say that the changes between 2 and 3 are minimal. I got an error that `wxADJUST_MINSIZE` was no longer defined, but changing it to its corresponding numeric value resulted in the aforementioned crash. The stack trace of the crash took me to an assertion error in [wxArtProvider::getBitmap](https://github.com/wxWidgets/wxWidgets/blob/b6cff426ce40a5bd8e0e51c6ad2f26d9510a597e/src/common/artprov.cpp#L238), which is as far as I got...

If you can get it to work with 3.2 on Linux I'll be happy to try to get it to work on OS X. Not yet familiar with the code base, but you gotta start somewhere.

**Comment by lcvisser** [comment]
@rburkey2005  Sorry, MacPorts got me confused. The [https://ports.macports.org/port/wxWidgets-3.2/summary] is called WxWidgets-3.2, but it indeed provides 3.1.4.

**Comment by lcvisser** [comment]
FYI: with 3.04 I don't get any compile errors, but still a segfault. This in `wxSystemSettingsNative::GetFont(wxSystemFont)`. I'll look into it more tomorrow.

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff20238e97 nanov2_allocate_from_block + 17
1   libsystem_malloc.dylib        	0x00007fff20238657 nanov2_allocate + 130
2   libsystem_malloc.dylib        	0x00007fff20238584 nanov2_malloc + 55
3   libsystem_malloc.dylib        	0x00007fff20252dfe _malloc_zone_malloc + 118
4   libc++abi.dylib               	0x00007fff203d8daa operator new(unsigned long) + 26
5   libwx_osx_cocoau_core-3.0.dylib	0x00000001069013c8 wxStockGDI::GetFont(wxStockGDI::Item) + 190
6   libwx_osx_cocoau_core-3.0.dylib	0x00000001069013f8 wxStockGDI::GetFont(wxStockGDI::Item) + 238
7   libwx_osx_cocoau_core-3.0.dylib	0x0000000106859410 wxSystemSettingsNative::GetFont(wxSystemFont) + 68
```

**Comment by rburkey2005** [comment]
@lcvisser You mean with 3.1.4?  (You say 3.04.)

**Comment by rburkey2005** [comment]
@lcvisser I pushed a change to the source code that fixes `wxADJUST_MINSIZE` (as you mentioned).  With that change, VirtualAGC builds using wxWidgets 3.1.4 and runs, as far as I can see.  There are no segfaults in Linux Mint 19 64-bit.

I can't say that it run _completely_ trouble-free, since when VirtualAGC opens it insists on popping up a lot of scary-looking warning boxes that complain about some of the ways wxWidgets is being used.  But after I click past the warnings, the program then seems to run normally.  I guess I'll have to do something about those warnings, eventually.

But still, in summary, I don't observe the problems you're experiencing.  They seem to be specific to Mac OS X.

**Comment by lcvisser** [comment]
> @lcvisser You mean with 3.1.4? (You say 3.04.)

I tried both 3.1.4 and 3.0.4. Sorry for the confusion.

The good news is: the quick fix you pushed makes it compile for 3.1.4 (3.0.4 still gives the SEGFAULT). I also get a bunch of warnings, but behold:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/6381487/111957982-fdce4200-8aec-11eb-8977-cc8ac068b8f0.png">


What I (think I) did:

 1. install WxWidgets from macports: `port install WxWidgets-3.2` (note: this installs WxWidgets 3.1.4...)
 2. `export cc=clang`
 3. `export CC=clang`
 4. `make MACOSX=yes FORCE_clang=yes clean install`

Note sure if (2) and (3) are necessary, but didn't hurt.

I had to skip on yaLVDC, yaACA3 and jWiz; the latter on account of me not having a joystick. I'm going to look into LVDC later, see why that won't compile. Here's the diff on the Makefile, for completeness sake:

```
diff --git a/Makefile b/Makefile
index 751a407..feb55ae 100644
--- a/Makefile
+++ b/Makefile
@@ -478,7 +478,7 @@ cbMISSIONS := $(patsubst %,%.cbp,$(cbMISSIONS))
 # The base set of targets to be built always.
 SUBDIRS = Tools yaLEMAP yaAGC yaAGS yaYUL ControlPulseSim yaUniverse
 SUBDIRS += yaAGC-Block1-Pultorak yaAGCb1 yaUplinkBlock1 Validation-Block1
-SUBDIRS += yaASM yaOBC yaLVDC
+SUBDIRS += yaASM yaOBC
 SUBDIRS += $(MISSIONS)
 
 ifndef NOGUI
@@ -498,9 +498,9 @@ endif
 ifndef FREEBSD
 SUBDIRS += yaACA2
 endif
-SUBDIRS += yaACA3
+#SUBDIRS += yaACA3
 SUBDIRS += yaTelemetry 
-SUBDIRS += jWiz
+#SUBDIRS += jWiz
 SUBDIRS += yaDSKYb1
 SUBDIRS += VirtualAGC
 endif # NOGUI
```

**Comment by rburkey2005** [comment]
@lcvisser I've pushed a number of source-code changes related to eliminating some pop-up warning windows &mdash; which you're apparently not seeing on Mac &mdash; which wxWidgets 3.1.x displays when VirtualAGC or yaDEDA2 start up.  The changes hopefully have no other behavioral impact, but you might want to pull the changes anyway.

I have _not_ (as you may have supposed) made any changes related to bypassing yaLVDC, yaACA3, or jWiz as of yet.  To do so without breaking existing builds is a more-convoluted process than I'd like to go through without having a better understanding of why they do not build, and of whether the inability to build them is permanent or not.  However, the absence of those programs shouldn't have any effect on you, so it's perfectly fine for you to locally bypass them as you've done.

**Comment by lcvisser** [comment]
I was seeing the same pop-up warnings as you were, I think. But I confirm now that they are gone with the changes you pushed.

I also managed to compile yaLVDC with a few changes, diff attached.

For yaACA3 and jWiz I needed some dependencies that I didn't want to install since I don't have a joystick. If I have time this weekend, I might look into that.



[virtualWire.c.txt](https://github.com/virtualagc/virtualagc/files/6185286/virtualWire.c.txt)

**Comment by rburkey2005** [comment]
@lcvisser Thanks, I pushed the change.

**Comment by lcvisser** [comment]
I needed to reinstall my macOS due to a botched OS update, hence I had a clean slate to try to build and use VirtualAGC on MacOS 12.0.1 (Monterey). I wanted to share (and maybe allow this issue to be closed) that everything works "out of the box", in the sense that I can compile and run the application and the demo without modifying the Makefile (not sure if anything changed there recently...?). I didn't try anything with joysticks or what not, but the below will result in a .app on your desktop that runs seemingly without errors:

1. Install Xcode command line tools
```bash
$ xcode-select --install
```
2. [Install Macports per the instructions](https://www.macports.org/install.php).
3. In a shell session:
```bash
$ sudo port install git +credential_osxkeychain
$ sudo port install wxWidgets-3.2
$ port contents wxWidgets-3.2  | grep bin  # note path
$ export PATH=/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/bin:$PATH  # path from command above
$ export cc=clang
$ export CC=clang
$ git clone https://github.com/virtualagc/virtualagc.git
$ cd virtualagc
$ make MACOSX=yes FORCE_clang=yes clean install
```

**Comment by rburkey2005** [comment]
@lcvisser Thanks!  I've updated the build instructions on the website, and I think I'll take your advice about closing this issue.  Thanks again!
