### ISSUE TITLE
Pi installation issue:  Unable to locate package libwxgtk2.8-0

### ISSUE THREAD

**Issue by RossMelbourne** [virtualagc/virtualagc#1103]
From the Pi installation instructions at https://www.ibiblio.org/apollo/download.html#Virtual_AGC_Installer_for_Raspberry_Pi 
The following command:
sudo apt-get install libwxgtk2.8-0 
Gives the following error message:
Unable to locate package libwxgtk2.8-0

**Comment by rburkey2005** [comment]
I haven't a more up-to-date Pi to test right now, but perhaps trying 3.0 in place of 2.8 might work.  Or wait a few days and I'll look into it.Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by RossMelbourne** [comment]
I tried:  sudo apt-get install libwxgtk3.0-0v5 and then I ran ../bin/VirtualAGC.  The following is the message I received:

pi@DSKY:~/VirtualAGC/Resources $ ../bin/VirtualAGC
../bin/VirtualAGC: error while loading shared libraries: libwx_gtk2u_richtext-2.8.so.0: cannot open shared object file: No such file or directory

**Comment by rburkey2005** [comment]
If you're talking about using the so-called "pre-built installation tarball", that won't work with wxGTK 3.0, since it was pre-built with the expectation of wxGTK 2.8 being available.  You'd have to build Virtual AGC from source after wxGTK 3.0 is installed.  Sorry I didn't make that clear before.The other option, of course, is that you can build wxGTK 2.8 itself from source if it is no longer available using apt-get.-----Original Message-----

**Comment by RossMelbourne** [comment]
I received the following error during the make process:
make[1]: Entering directory '/home/pi/VirtualAGC/virtualagc/yaDEDA2'
g++ \
	`wx-config --cxxflags`  \
	-o yaDEDA2 yaDEDA2.cpp -x c ../yaAGC/agc_utilities.c ../yaAGC/agc_engine.c ../yaAGC/Backtrace.c ../yaAGC/random.c ../yaAGC/SocketAPI.c ../yaAGC/rfopen.c \
	`wx-config --libs` \
	
/bin/sh: 1: wx-config: not found
/bin/sh: 1: wx-config: not found
In file included from yaDEDA2.cpp:50:
yaDEDA2.h:36:10: fatal error: wx/wx.h: No such file or directory
 #include <wx/wx.h>
          ^~~~~~~~~
compilation terminated.

**Comment by rburkey2005** [comment]
A message that wx-config wasn't found would usually mean that you installed libwxgtk3.0 but did not install libwxgtk3.0-dev.

**Comment by rburkey2005** [comment]
Also, I'd imagine from the instructions for building Virtual AGC on Raspberry Pi (http://www.ibiblio.org/apollo/download.html#Raspberry_Pi_Raspbian_), that you would have needed to install wx3.0-headers as well.

**Comment by RossMelbourne** [comment]
Building from source worked great, thank you.

**Comment by rburkey2005** [comment]
Cool!Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by Thymo-** [comment]
I guess this could be closed now.

**Comment by rburkey2005** [comment]
Done!
