### ISSUE TITLE
yaDEDA2.h:36:10: fatal error: wx/wx.h: No such file or directory

### ISSUE THREAD

**Issue by ayyucedemirbas** [virtualagc/virtualagc#1069]
I am trying to compile VirtualAGC. I get this error message

In file included from yaDEDA2.cpp:50:0:
yaDEDA2.h:36:10: fatal error: wx/wx.h: No such file or directory
 #include <wx/wx.h>
          ^~~~~~~~~
compilation terminated.
Makefile:108: recipe for target 'yaDEDA2' failed
make[1]: *** [yaDEDA2] Error 1

**Comment by rburkey2005** [comment]
@ayyucedemirbas Without knowing what operating system you're working on, it's hard to be too specific with an answer :-), but I had a similar complaint a few days ago.  Take a look at bug #1068, and see if that's relevant to what's happening to you.

**Comment by ayyucedemirbas** [comment]
Sorry, it's Ubuntu 18.04

Thank you so much!

**Comment by rburkey2005** [comment]
That makes it easier.   It sounds to me as if you don't have the wxWidgets "development" package installed.  I'm not sure exactly what it would be called on Ubuntu 18.04, but it could be something like wxgtk-dev, wxgtk-devel, libwxgtk-dev, libwxgtk3-dev, etc.  On my Linux Mint system (based on Ubuntu 14.04 or 16.04), it's libwxgtk3.0-dev.

**Comment by ayyucedemirbas** [comment]
It worked! :) Thanks again!

**Comment by rburkey2005** [comment]
You're quite welcome.  I'll close out the bug report.

**Comment by masngudi1** [comment]
I use windows 8 for compile and have problem below;

$ mingw32-make
g++ -c -mthreads -O0 -w -Wno-invalid-offsetof -Wformat -g -D__WXDEBUG__ -DWIN32 -D__WXMSW__ -D_WINDOWS -DNOPCH -I"/boost" -I"/DB/build_unix" -I"/OpenSSL/include" -I"/wxWidgets/lib/vc_lib/mswd" -I"/wxWidgets/include" -o headers.h.gch headers.h
headers.h:15:10: fatal error: wx/wx.h: No such file or directory
   15 | #include <wx/wx.h>
      |          ^~~~~~~~~
compilation terminated.
mingw32-make: *** [makefile:37: headers.h.gch] Error 1

**Comment by rburkey2005** [comment]
@masngudi1 I could be mistaken, those steps don't seem to correspond to [the posted instructions for building Virtual AGC on Windows](https://www.ibiblio.org/apollo/download.html#Windows).  If I'm right, perhaps you could give those a try.  Unfortunately (depending on your point of view), I'm still on Windows 7, and I only fire it up once every couple of years, so am not in a position to provide any assistance for later versions.

**Comment by 7ofNine** [comment]
@masgnudi I never used Windows 8 and I have never tried to build it using MSYS/MSYS2 I typically compile directly using MSVC but I haven't done that either in a while. Independent of that I have the somewhat stupid question if you have the wxWidgets installed and all the paths properly set up. It simply doesn't find the main header file which makes it suspicious of a missing or improper installation. I don't know if MSYS still supports the installation of wxWidgets under Windows 8. The other question is if you are running it in the correct environment? Why are you using mingw32-make? The windows build recipe asks to run in msys shell where this version of make can cause trouble. Run make in msys shell.

**Comment by masngudi1** [comment]
@7ofNine thank for the response, I try use Msys and the result is same

$ make
g++ -c -mthreads -O0 -w -Wno-invalid-offsetof -Wformat -g -D__WXDEBUG__ -DWIN32 -D__WXMSW__ -D_WINDOWS -DNOPCH -I"/boost" -I"/DB/build_unix" -I"/OpenSSL/include" -I"/wxWidgets/lib/vc_lib/mswd" -I"/wxWidgets/include" -o headers.h.gch headers.h
/bin/sh: line 1: g++: command not found
make: *** [makefile:37: headers.h.gch] Error 127

**Comment by masngudi1** [comment]
@rburkey2005 thank for the response

hope your advice can fixed my problem during compile source code

**Comment by 7ofNine** [comment]
@masngudi1 in your second trial the result is actually not the same. This time the g++ i.e. the compiler was not found. You should verify that you have all the necessary packages installed in your msys environment. pacman is not that difficult to use. If you have only have a raw msys installation all the tools are typically not installed. Interestingly you have make but not g++. Are you accessing the correct make or do you have somewhere another make in the path.

**Comment by masngudi1** [comment]
yes that I try with Msys32
for Msys64 the result is below

$ make
g++ -c -mthreads -O0 -w -Wno-invalid-offsetof -Wformat -g -D__WXDEBUG__ -DWIN32 -D__WXMSW__ -D_WINDOWS -DNOPCH -I"/boost" -I"/DB/build_unix" -I"/OpenSSL/include" -I"/wxWidgets/lib/vc_lib/mswd" -I"/wxWidgets/include" -o headers.h.gch headers.h
headers.h:15:10: fatal error: wx/wx.h: No such file or directory
   15 | #include <wx/wx.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [makefile:37: headers.h.gch] Error 1

**Comment by masngudi1** [comment]
version of g++ below


$ g++ --version
g++.exe (Rev2, Built by MSYS2 project) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by rburkey2005** [comment]
Did you install wxWidgets?Sent on my Samsung Galaxy A51
-------- Original message --------From: masngudi1 ***@***.***> Date: 11/4/23  7:08 PM  (GMT-06:00) To: virtualagc/virtualagc ***@***.***> Cc: Ronald Burkey ***@***.***>, Mention ***@***.***> Subject: Re: [virtualagc/virtualagc] yaDEDA2.h:36:10: fatal error: wx/wx.h: No
  such file or directory (#1069) 
yes that I try with Msys32
for Msys64 the result is below
$ make
g++ -c -mthreads -O0 -w -Wno-invalid-offsetof -Wformat -g -D__WXDEBUG__ -DWIN32 -D__WXMSW__ -D_WINDOWS -DNOPCH -I"/boost" -I"/DB/build_unix" -I"/OpenSSL/include" -I"/wxWidgets/lib/vc_lib/mswd" -I"/wxWidgets/include" -o headers.h.gch headers.h
headers.h:15:10: fatal error: wx/wx.h: No such file or directory
15 | #include <wx/wx.h>
|          ^~~~~~~~~
compilation terminated.
make: *** [makefile:37: headers.h.gch] Error 1

**Comment by masngudi1** [comment]
@rburkey2005 yes I install wxwidgets

**Comment by masngudi1** [comment]
Dependencies for compile
------------
Libraries you need to obtain separately to build:

              default path   download
wxWidgets      \wxWidgets     http://www.wxwidgets.org/downloads/
OpenSSL        \OpenSSL       http://www.openssl.org/source/
Berkeley DB    \DB            http://www.oracle.com/technology/software/products/berkeley-db/index.html
Boost          \Boost         http://www.boost.org/users/download/

Their licenses:
wxWidgets      LGPL 2.1 with very liberal exceptions
OpenSSL        Old BSD license with the problematic advertising requirement
Berkeley DB    New BSD license with additional requirement that linked software must be free open source
Boost          MIT-like license

**Comment by rburkey2005** [comment]
Okay ... a couple of points:

1. If wxWidgets is installed correctly, then _from an Msys command line_, if you type the command `wx-config --version`, you should get a meaningful response such as "2.8.12", rather than something like "command not found".  If you get a "command not found", it means wxWidgets was not installed in the manner expected.
2. Did you install wxWidgets _within Msys_ &mdash; i.e., did you build it from the Msys command line &mdash; or did you install it in some "Windows-like" way?  You need to install it _from Msys_.  I don't think a normal Windows installation (say, using the normal Windows command line) gets you anything usable by Msys.

**Comment by rburkey2005** [comment]
@masngudi1  It took me a while to notice, but I fear you've come to the wrong place.

Realize that this is the problem-reporting page for **the Virtual AGC Project**.  You don't actually appear to be trying to compile Virtual AGC.  There's not a single Virtual AGC source-code file in the error messages you've been posting.  I don't know _what_ you're trying to compile, but if it's not Virtual AGC software, there's no help for you here.

**Comment by masngudi1** [comment]
@rburkey2005 
 
I just try to compile bitcoin source code, I already follow instruction from bitcointalk but the result as you see above, 
this link instruction from bitcointalk
https://bitcointalk.org/index.php?topic=149479.0

**Comment by masngudi1** [comment]
@rburkey2005 

but I prefer to follow instruction from this video but the result is same
https://www.youtube.com/watch?v=5ArVcse29ME&t=169s

=======
some instructions by satoshi for compile
BitCoin v0.01 ALPHA

Copyright (c) 2009 Satoshi Nakamoto
Distributed under the MIT/X11 software license, see the accompanying
file license.txt or http://www.opensource.org/licenses/mit-license.php.
This product includes software developed by the OpenSSL Project for use in
the OpenSSL Toolkit (http://www.openssl.org/).  This product includes
cryptographic software written by Eric Young (eay@cryptsoft.com).


Compilers Supported
-------------------
MinGW GCC (v3.4.5)
Microsoft Visual C++ 6.0 SP6


Dependencies
------------
Libraries you need to obtain separately to build:

              default path   download
wxWidgets      \wxWidgets     http://www.wxwidgets.org/downloads/
OpenSSL        \OpenSSL       http://www.openssl.org/source/
Berkeley DB    \DB            http://www.oracle.com/technology/software/products/berkeley-db/index.html
Boost          \Boost         http://www.boost.org/users/download/

Their licenses:
wxWidgets      LGPL 2.1 with very liberal exceptions
OpenSSL        Old BSD license with the problematic advertising requirement
Berkeley DB    New BSD license with additional requirement that linked software must be free open source
Boost          MIT-like license


OpenSSL
-------
Bitcoin does not use any encryption.  If you want to do a no-everything
build of OpenSSL to exclude encryption routines, a few patches are required.
(OpenSSL v0.9.8h)

Edit engines\e_gmp.c and put this #ifndef around #include <openssl/rsa.h>
  #ifndef OPENSSL_NO_RSA
  #include <openssl/rsa.h>
  #endif

Add this to crypto\err\err_all.c before the ERR_load_crypto_strings line:
  void ERR_load_RSA_strings(void) { }

Edit ms\mingw32.bat and replace the Configure line's parameters with this
no-everything list.  You have to put this in the batch file because batch
files can't handle more than 9 parameters.
  perl Configure mingw threads no-rc2 no-rc4 no-rc5 no-idea no-des no-bf no-cast no-aes no-camellia no-seed no-rsa no-dh

Also REM out the following line in ms\mingw32.bat.  The build fails after it's
already finished building libeay32, which is all we care about, but the
failure aborts the script before it runs dllwrap to generate libeay32.dll.
  REM  if errorlevel 1 goto end

Build
  ms\mingw32.bat

If you want to use it with MSVC, generate the .lib file
  lib /machine:i386 /def:ms\libeay32.def /out:out\libeay32.lib


Berkeley DB
-----------
MinGW with MSYS:
cd \DB\build_unix
sh ../dist/configure --enable-mingw --enable-cxx
make


Boost
-----
You may need Boost version 1.35 to build with MSVC 6.0.  I couldn't get
version 1.37 to compile with MSVC 6.0.

**Comment by masngudi1** [comment]
@rburkey2005
thank you in advance for your kind help and response

**Comment by rburkey2005** [comment]
Yes ... well, as I said, nothing whatever to do with Virtual AGC. Sent on my Samsung Galaxy A51
-------- Original message --------From: masngudi1 ***@***.***> Date: 11/4/23  9:03 PM  (GMT-06:00) To: virtualagc/virtualagc ***@***.***> Cc: Ronald Burkey ***@***.***>, Mention ***@***.***> Subject: Re: [virtualagc/virtualagc] yaDEDA2.h:36:10: fatal error: wx/wx.h: No
  such file or directory (#1069) 
@rburkey2005
I just try to compile bitcoin source code, I already follow instruction from bitcointalk but the result as you see above,
this link instruction from bitcointalk
https://bitcointalk.org/index.php?topic=149479.0
